name: Deploy Rhythm Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.59
    steps:
      - uses: actions/checkout@v4
      - name: Configure web build
        run: emcmake cmake -S . -B build/web -DCMAKE_BUILD_TYPE=Release
      - name: Build transpose_wasm target
        run: cmake --build build/web --target transpose_wasm
      - name: Build web asset bundle
        run: cmake --build build/web --target rhythm_web_assets
      - name: Stage deployable assets
        run: |
          mkdir -p deploy
          cp -r build/web/web/. deploy/
          cp -r web/. deploy/
          if [ -f build/web/web/build-info.js ]; then
            cp build/web/web/build-info.js deploy/build-info.js
          fi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: deploy/

  deploy:
    needs: build
    runs-on: ubuntu-latest # No container here!
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: deploy

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.COSC3320_RHYTHMBOT_SSH }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.COSC_RHYTHMBOT_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync web assets to server
        run: |
          scp -r deploy/. ${{ secrets.COSC_RHYTHMBOT_SERVER_USER }}@${{ secrets.COSC_RHYTHMBOT_SERVER_HOST }}:/home/rhythmbot/rhythm-web/
